### ISSUE TITLE
Implement Master Server

### ISSUE THREAD

**Issue by zojw** [zojw/shared-storage#2]
## Phase 1

Support manipulate bucket both in s3 and cache server

- [x] Support manipulate bucket operation
- [x] Support fake Placement Lookup operation
- [x] Export as two gRPC service

## Phase 2 

Cooperate with cache server 

- [ ] Implement heartbeat to cache server
- [ ] Maintain object placement cache and replace fake impl in phase 1 

## Phase 3

Support replica cache server

- [ ] Recovery placement info from S3 when master restart
- [ ] Implement reconcile loop to add  or remove object in node with CacheServer's maintain service
